// ─── Mock data used when Supabase is not yet connected ───────────────────────
// Replace these with real Supabase queries once your project is set up.

export const MOCK_CATEGORIES = [
  { category_id: 1, name: 'Politics', description: 'Political news and analysis' },
  { category_id: 2, name: 'Business', description: 'Business and finance news' },
  { category_id: 3, name: 'Tech', description: 'Technology and innovation' },
  { category_id: 4, name: 'Science', description: 'Science and research' },
  { category_id: 5, name: 'Entertainment', description: 'Entertainment and culture' },
  { category_id: 6, name: 'Sports', description: 'Sports news and results' },
  { category_id: 7, name: 'Freelance', description: 'Freelance contributor articles' },
]

export const MOCK_USERS = [
  {
    user_id: 1, name: 'Alex Johnson', role: 'journalist' as const,
    email: 'alex@026connet!.com',
    bio: 'Experienced science and technology journalist with 8 years in the field.',
    profile_image: 'https://i.pravatar.cc/150?img=1',
    status: 'active' as const, password_hash: '', created_at: '2023-01-10',
    articles: 28, earnings: 2340.75, subscribers: 1250,
  },
  {
    user_id: 2, name: 'Admin User', role: 'admin' as const,
    email: 'admin@026connet!.com', bio: 'Platform administrator.',
    profile_image: 'https://i.pravatar.cc/150?img=2',
    status: 'active' as const, password_hash: '', created_at: '2023-01-01',
    articles: 0, earnings: 0, subscribers: 0,
  },
  {
    user_id: 3, name: 'Sarah Mitchell', role: 'journalist' as const,
    email: 'sarah@026connet!.com',
    bio: 'Environmental journalist covering climate, energy, and sustainability.',
    profile_image: 'https://i.pravatar.cc/150?img=5',
    status: 'active' as const, password_hash: '', created_at: '2023-02-14',
    articles: 31, earnings: 1890.50, subscribers: 980,
  },
  {
    user_id: 4, name: 'Mark Johnson', role: 'journalist' as const,
    email: 'mark@026connet!.com', bio: 'Political analyst and senior correspondent.',
    profile_image: 'https://i.pravatar.cc/150?img=3',
    status: 'active' as const, password_hash: '', created_at: '2023-03-20',
    articles: 52, earnings: 3200.00, subscribers: 2100,
  },
  {
    user_id: 5, name: 'Alice Carter', role: 'journalist' as const,
    email: 'alice@026connet!.com', bio: 'Business and finance journalist.',
    profile_image: 'https://i.pravatar.cc/150?img=9',
    status: 'active' as const, password_hash: '', created_at: '2023-04-05',
    articles: 23, earnings: 1450.00, subscribers: 760,
  },
]

export const MOCK_ARTICLES = [
  {
    article_id: 1,
    title: 'Research Team Discovers New Exoplanet in the Habitable Zone',
    slug: 'new-exoplanet-habitable-zone',
    content: `A team of astronomers has made a groundbreaking discovery — a new exoplanet sitting firmly within the habitable zone of its host star. The planet, designated Kepler-452c, is approximately 1.6 times the size of Earth and orbits a G-type star remarkably similar to our Sun.\n\nThe discovery was made using data from the James Webb Space Telescope combined with ground-based observations. Scientists believe the planet may have liquid water on its surface, a key prerequisite for life as we know it.\n\n"This is perhaps the most exciting find of our generation," said lead researcher Dr. Elena Vasquez. "The atmospheric composition readings suggest the presence of water vapor and carbon dioxide."\n\nFurther observations are planned over the next 18 months to better characterize the planet's atmosphere. The team plans to use spectroscopic analysis to search for biosignatures — chemical indicators of biological activity.`,
    category_id: 4, author_id: 1,
    source_reference: 'https://nasa.gov',
    status: 'published' as const, monetization_type: 'free' as const,
    featured_image: 'https://picsum.photos/id/1015/800/450',
    views: 12450, earnings: 320.00,
    created_at: '2024-04-20', updated_at: '2024-04-20',
    featured: true,
    tags: ['Space', 'Exoplanet', 'NASA', 'Astronomy'],
    sources: [
      { name: 'NASA Official Report', url: 'https://nasa.gov' },
      { name: 'ESO Research Paper', url: 'https://eso.org' },
      { name: 'Scientific American', url: 'https://scientificamerican.com' },
    ],
    comments: [
      { id: 1, author: 'David K.', avatar: 'https://i.pravatar.cc/40?img=10', text: 'Amazing development! This could change everything.', time: '1h ago', likes: 24 },
      { id: 2, author: 'Maria L.', avatar: 'https://i.pravatar.cc/40?img=11', text: 'The James Webb telescope keeps delivering incredible results.', time: '3h ago', likes: 18 },
    ],
    author: { user_id: 1, name: 'Alex Johnson', profile_image: 'https://i.pravatar.cc/150?img=1', bio: 'Experienced science and technology journalist.' },
    category: { name: 'Science' },
  },
  {
    article_id: 2,
    title: 'Breakthrough in Renewable Energy: New Solar Technology Unveiled',
    slug: 'solar-technology-breakthrough',
    content: `A groundbreaking new solar technology has been unveiled that could transform the renewable energy landscape. The new panels achieve a record 47% photovoltaic efficiency — nearly double current commercial solar panels.\n\nDeveloped by researchers at MIT in collaboration with a consortium of energy companies, the breakthrough leverages a multi-junction cell design combined with light-concentrating micro-lenses etched directly onto the panel surface.\n\nManufacturing costs are projected to be competitive with traditional silicon panels within three years. Early pilot installations are already underway in Kenya, Germany, and California.\n\n"This changes the economics of renewable energy entirely," said Dr. James Okoro. "At these efficiencies, solar becomes the cheapest form of energy generation in human history."`,
    category_id: 3, author_id: 3,
    source_reference: 'https://reuters.com',
    status: 'published' as const, monetization_type: 'free' as const,
    featured_image: 'https://picsum.photos/id/106/800/450',
    views: 8750, earnings: 210.50,
    created_at: '2024-04-15', updated_at: '2024-04-15',
    featured: true,
    tags: ['Solar', 'Energy', 'CleanTech', 'MIT'],
    sources: [
      { name: 'Reuters', url: 'https://reuters.com' },
      { name: 'BBC News', url: 'https://bbc.com' },
    ],
    comments: [
      { id: 1, author: 'David K.', avatar: 'https://i.pravatar.cc/40?img=10', text: 'Amazing! This could change the future of energy.', time: '1h ago', likes: 42 },
      { id: 2, author: 'Priya S.', avatar: 'https://i.pravatar.cc/40?img=12', text: 'Finally! Been waiting for solar to reach this efficiency.', time: '2h ago', likes: 31 },
    ],
    author: { user_id: 3, name: 'Sarah Mitchell', profile_image: 'https://i.pravatar.cc/150?img=5', bio: 'Environmental journalist covering climate and energy.' },
    category: { name: 'Tech' },
  },
  {
    article_id: 3,
    title: 'Tech Giants Battle for the Metaverse',
    slug: 'tech-giants-battle-metaverse',
    content: `The metaverse wars are heating up as major technology companies pour billions into virtual world development. Meta, Apple, Microsoft, and a wave of startups are competing for dominance in what many analysts are calling the next frontier of the internet.\n\nMeta's latest quarterly earnings revealed $4.2 billion invested in Reality Labs, while Apple's Vision Pro has seen surprising adoption in enterprise settings. Microsoft's Mesh platform quietly crossed 10 million monthly users.\n\nGoldman Sachs projects the metaverse economy could reach $8 trillion by 2030.`,
    category_id: 3, author_id: 1,
    source_reference: 'https://bbc.com',
    status: 'under_review' as const, monetization_type: 'paywall' as const,
    featured_image: 'https://picsum.photos/id/180/800/450',
    views: 0, earnings: 0,
    created_at: '2024-04-21', updated_at: '2024-04-21',
    featured: false,
    tags: ['Metaverse', 'Meta', 'Apple', 'VR'],
    sources: [{ name: 'BBC Technology', url: 'https://bbc.com/technology' }],
    comments: [],
    author: { user_id: 1, name: 'Alex Johnson', profile_image: 'https://i.pravatar.cc/150?img=1', bio: 'Tech journalist.' },
    category: { name: 'Tech' },
  },
  {
    article_id: 4,
    title: 'Global Politics: Tensions Rise in Eastern Europe',
    slug: 'global-politics-eastern-europe',
    content: `Diplomatic tensions in Eastern Europe have reached their highest point in a decade, with multiple border disputes and trade disagreements straining relations between key nations.\n\nForeign ministers from six countries are scheduled to meet in Vienna next week for emergency negotiations.`,
    category_id: 1, author_id: 4,
    source_reference: 'https://reuters.com',
    status: 'published' as const, monetization_type: 'free' as const,
    featured_image: 'https://picsum.photos/id/342/800/450',
    views: 6320, earnings: 145.00,
    created_at: '2024-04-18', updated_at: '2024-04-18',
    featured: false,
    tags: ['Politics', 'Europe', 'Diplomacy'],
    sources: [{ name: 'Reuters', url: 'https://reuters.com' }],
    comments: [],
    author: { user_id: 4, name: 'Mark Johnson', profile_image: 'https://i.pravatar.cc/150?img=3', bio: 'Political analyst.' },
    category: { name: 'Politics' },
  },
  {
    article_id: 5,
    title: 'Global Markets Rally on Fed Decision',
    slug: 'global-markets-fed-decision',
    content: `Global stock markets surged following the Federal Reserve's decision to hold interest rates steady. The S&P 500 gained 2.3% on the day, while European indices posted their best weekly performance since January 2023.`,
    category_id: 2, author_id: 5,
    source_reference: 'https://bloomberg.com',
    status: 'published' as const, monetization_type: 'sponsored' as const,
    featured_image: 'https://picsum.photos/id/20/800/450',
    views: 4100, earnings: 280.00,
    created_at: '2024-04-17', updated_at: '2024-04-17',
    featured: false,
    tags: ['Markets', 'Finance', 'Fed', 'Stocks'],
    sources: [{ name: 'Bloomberg', url: 'https://bloomberg.com' }],
    comments: [],
    author: { user_id: 5, name: 'Alice Carter', profile_image: 'https://i.pravatar.cc/150?img=9', bio: 'Business journalist.' },
    category: { name: 'Business' },
  },
  {
    article_id: 6,
    title: 'African Tech Startups Raise Record $6.5B in 2023',
    slug: 'african-tech-startups-surge',
    content: `African technology startups raised a record $6.5 billion in venture capital funding in 2023, with fintech, healthtech, and agritech leading the charge. Lagos, Nairobi, Cairo, and Cape Town are emerging as tier-one startup ecosystems.\n\nThe trend is driven by a young, mobile-first population, expanding internet penetration, and a growing middle class.`,
    category_id: 2, author_id: 3,
    source_reference: 'https://techcrunch.com',
    status: 'published' as const, monetization_type: 'free' as const,
    featured_image: 'https://picsum.photos/id/0/800/450',
    views: 3890, earnings: 95.00,
    created_at: '2024-04-14', updated_at: '2024-04-14',
    featured: false,
    tags: ['Africa', 'Startups', 'Tech', 'VC'],
    sources: [{ name: 'TechCrunch Africa', url: 'https://techcrunch.com' }],
    comments: [],
    author: { user_id: 3, name: 'Sarah Mitchell', profile_image: 'https://i.pravatar.cc/150?img=5', bio: 'Environmental journalist.' },
    category: { name: 'Business' },
  },
  {
    article_id: 7,
    title: 'Investigative Report: Ad Revenue Strategy Shifts for African Media',
    slug: 'ad-revenue-strategy-african-media',
    content: `A deep dive into the advertising shifts transforming digital publishers across Africa. The report highlights sponsored content trends, subscription incentives, and the new premium reader economy affecting independent media outlets.

Advertisers are moving budgets to trusted local publishers with engaged audiences. Journalists are being encouraged to build transparent affiliate-style partnerships and produce branded editorial without sacrificing integrity.`,
    category_id: 2, author_id: 5,
    source_reference: 'https://africanbusinessmag.com',
    status: 'draft' as const, monetization_type: 'sponsored' as const,
    featured_image: 'https://picsum.photos/id/107/800/450',
    views: 0, earnings: 0,
    created_at: '2024-04-23', updated_at: '2024-04-23',
    featured: false,
    tags: ['Ads', 'Media', 'Subscriptions'],
    sources: [{ name: 'African Business', url: 'https://africanbusinessmag.com' }],
    comments: [],
    author: { user_id: 5, name: 'Alice Carter', profile_image: 'https://i.pravatar.cc/150?img=9', bio: 'Business journalist.' },
    category: { name: 'Business' },
  },
  {
    article_id: 8,
    title: 'Editorial Review: Why This Article Was Rejected',
    slug: 'editorial-review-rejected-article',
    content: `A review of editorial standards and the importance of fact-checking in modern newsrooms. This article explores how rejected submissions are improved through transparent feedback and journalist collaboration.

Rejected pieces are not failures — they are opportunities to refine reporting, tighten sourcing, and maintain reader trust across platforms.`,
    category_id: 1, author_id: 4,
    source_reference: 'https://journalism.co',
    status: 'rejected' as const, monetization_type: 'free' as const,
    featured_image: 'https://picsum.photos/id/108/800/450',
    views: 340, earnings: 0,
    created_at: '2024-04-22', updated_at: '2024-04-22',
    featured: false,
    tags: ['Editorial', 'Standards', 'Review'],
    sources: [{ name: 'Journalism.co', url: 'https://journalism.co' }],
    comments: [],
    author: { user_id: 4, name: 'Mark Johnson', profile_image: 'https://i.pravatar.cc/150?img=3', bio: 'Political analyst.' },
    category: { name: 'Politics' },
  },
]

export const MOCK_JOURNALIST_STATS = {
  totalViews: 125400,
  totalEarnings: 2340.75,
  thisMonthEarnings: 865.50,
  articlesPublished: 28,
  drafts: 3,
  underReview: 1,
  newSubscribers: 1250,
  totalComments: 985,
  shares: 430,
  avgEngagement: 9.3,
}

export const MOCK_ADMIN_STATS = {
  totalArticles: 1245,
  freelanceSubmissions: 128,
  activeUsers: 58400,
  monthlyVisitors: 120000,
  totalRevenue: 67980,
  thisMonthPayout: 4320,
  pendingPayouts: 560.00,
}

export type MockArticle = typeof MOCK_ARTICLES[number]
export type MockUser = typeof MOCK_USERS[number]
